from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field, ConfigDict
from .domain import StartupProfile, AgentResult

class AgentName(str, Enum):
    """Names of the specialist agents in the system."""
    MARKET_RESEARCH = "market_research"
    COMPETITOR = "competitor"
    FINANCIAL = "financial"
    LEGAL = "legal"
    SUMMARIZATION = "summarization"

class WorkflowStatus(str, Enum):
    """Current execution status of the orchestrator workflow."""
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class AgentTask(BaseModel):
    """A task allocated to a specific agent in the due diligence workflow."""
    model_config = ConfigDict(use_enum_values=True)

    task_id: str = Field(..., examples=["task_market_01"])
    agent_name: AgentName = Field(..., examples=[AgentName.MARKET_RESEARCH])
    startup_profile: StartupProfile
    depends_on: list[str] = Field(default_factory=list, examples=[[]])
    priority: int = Field(default=0, examples=[1])

class AgentTaskResult(BaseModel):
    """Result payload of a completed agent task."""
    model_config = ConfigDict(use_enum_values=True)

    task_id: str = Field(..., examples=["task_market_01"])
    agent_name: AgentName = Field(..., examples=[AgentName.MARKET_RESEARCH])
    result: AgentResult
    completed_at: datetime = Field(..., examples=["2026-06-11T00:00:00Z"])

class WorkflowState(BaseModel):
    """State management for a startup due diligence execution run."""
    model_config = ConfigDict(use_enum_values=True)

    startup_name: str = Field(..., examples=["VentureMind Inc."])
    tasks: list[AgentTask] = Field(default_factory=list)
    results: dict[str, AgentTaskResult] = Field(default_factory=dict)
    status: WorkflowStatus = Field(default=WorkflowStatus.PENDING, examples=[WorkflowStatus.PENDING])
    started_at: datetime = Field(..., examples=["2026-06-11T00:00:00Z"])
    completed_at: datetime | None = Field(default=None, examples=[None])

class OrchestratorPlan(BaseModel):
    """Plan generated by the orchestrator for executing agent tasks."""
    model_config = ConfigDict(use_enum_values=True)

    startup_name: str = Field(..., examples=["VentureMind Inc."])
    parallel_groups: list[list[str]] = Field(..., examples=[[["task_market_01", "task_legal_01"]]])
    sequential_deps: dict[str, list[str]] = Field(default_factory=dict, examples=[{"task_summary_01": ["task_market_01"]}])
    estimated_duration_ms: int = Field(..., examples=[12000])
